/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedClientRouteRouteImport } from './routes/_authenticated/client/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedClientUsersRouteImport } from './routes/_authenticated/client/users'
import { Route as AuthenticatedClientPurchaseOrdersRouteImport } from './routes/_authenticated/client/purchase-orders'
import { Route as AuthenticatedClientPaymentsRouteImport } from './routes/_authenticated/client/payments'
import { Route as AuthenticatedClientLedgersRouteImport } from './routes/_authenticated/client/ledgers'
import { Route as AuthenticatedClientDocumentsRouteImport } from './routes/_authenticated/client/documents'
import { Route as AuthenticatedClientDispatchesRouteImport } from './routes/_authenticated/client/dispatches'
import { Route as AuthenticatedClientBalanceConfirmationsRouteImport } from './routes/_authenticated/client/balance-confirmations'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminRefundLettersRouteImport } from './routes/_authenticated/admin/refund-letters'
import { Route as AuthenticatedAdminRatesRouteImport } from './routes/_authenticated/admin/rates'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminPoQueueRouteImport } from './routes/_authenticated/admin/po-queue'
import { Route as AuthenticatedAdminPoFormatsRouteImport } from './routes/_authenticated/admin/po-formats'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminDispatchQueueRouteImport } from './routes/_authenticated/admin/dispatch-queue'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin/clients'
import { Route as AuthenticatedAdminBalanceConfirmationsRouteImport } from './routes/_authenticated/admin/balance-confirmations'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated/admin/approvals'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientRouteRoute =
  AuthenticatedClientRouteRouteImport.update({
    id: '/client',
    path: '/client',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedClientUsersRoute =
  AuthenticatedClientUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientPurchaseOrdersRoute =
  AuthenticatedClientPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientPaymentsRoute =
  AuthenticatedClientPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientLedgersRoute =
  AuthenticatedClientLedgersRouteImport.update({
    id: '/ledgers',
    path: '/ledgers',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientDocumentsRoute =
  AuthenticatedClientDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientDispatchesRoute =
  AuthenticatedClientDispatchesRouteImport.update({
    id: '/dispatches',
    path: '/dispatches',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedClientBalanceConfirmationsRoute =
  AuthenticatedClientBalanceConfirmationsRouteImport.update({
    id: '/balance-confirmations',
    path: '/balance-confirmations',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRefundLettersRoute =
  AuthenticatedAdminRefundLettersRouteImport.update({
    id: '/refund-letters',
    path: '/refund-letters',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRatesRoute = AuthenticatedAdminRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPoQueueRoute =
  AuthenticatedAdminPoQueueRouteImport.update({
    id: '/po-queue',
    path: '/po-queue',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPoFormatsRoute =
  AuthenticatedAdminPoFormatsRouteImport.update({
    id: '/po-formats',
    path: '/po-formats',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDispatchQueueRoute =
  AuthenticatedAdminDispatchQueueRouteImport.update({
    id: '/dispatch-queue',
    path: '/dispatch-queue',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBalanceConfirmationsRoute =
  AuthenticatedAdminBalanceConfirmationsRouteImport.update({
    id: '/balance-confirmations',
    path: '/balance-confirmations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/client': typeof AuthenticatedClientRouteRouteWithChildren
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/balance-confirmations': typeof AuthenticatedAdminBalanceConfirmationsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/dispatch-queue': typeof AuthenticatedAdminDispatchQueueRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/po-formats': typeof AuthenticatedAdminPoFormatsRoute
  '/admin/po-queue': typeof AuthenticatedAdminPoQueueRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/admin/refund-letters': typeof AuthenticatedAdminRefundLettersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/client/balance-confirmations': typeof AuthenticatedClientBalanceConfirmationsRoute
  '/client/dispatches': typeof AuthenticatedClientDispatchesRoute
  '/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/client/ledgers': typeof AuthenticatedClientLedgersRoute
  '/client/payments': typeof AuthenticatedClientPaymentsRoute
  '/client/purchase-orders': typeof AuthenticatedClientPurchaseOrdersRoute
  '/client/users': typeof AuthenticatedClientUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/balance-confirmations': typeof AuthenticatedAdminBalanceConfirmationsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/dispatch-queue': typeof AuthenticatedAdminDispatchQueueRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/po-formats': typeof AuthenticatedAdminPoFormatsRoute
  '/admin/po-queue': typeof AuthenticatedAdminPoQueueRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/admin/refund-letters': typeof AuthenticatedAdminRefundLettersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/client/balance-confirmations': typeof AuthenticatedClientBalanceConfirmationsRoute
  '/client/dispatches': typeof AuthenticatedClientDispatchesRoute
  '/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/client/ledgers': typeof AuthenticatedClientLedgersRoute
  '/client/payments': typeof AuthenticatedClientPaymentsRoute
  '/client/purchase-orders': typeof AuthenticatedClientPurchaseOrdersRoute
  '/client/users': typeof AuthenticatedClientUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/client': typeof AuthenticatedClientRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/balance-confirmations': typeof AuthenticatedAdminBalanceConfirmationsRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/dispatch-queue': typeof AuthenticatedAdminDispatchQueueRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/po-formats': typeof AuthenticatedAdminPoFormatsRoute
  '/_authenticated/admin/po-queue': typeof AuthenticatedAdminPoQueueRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/_authenticated/admin/refund-letters': typeof AuthenticatedAdminRefundLettersRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/client/balance-confirmations': typeof AuthenticatedClientBalanceConfirmationsRoute
  '/_authenticated/client/dispatches': typeof AuthenticatedClientDispatchesRoute
  '/_authenticated/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/_authenticated/client/ledgers': typeof AuthenticatedClientLedgersRoute
  '/_authenticated/client/payments': typeof AuthenticatedClientPaymentsRoute
  '/_authenticated/client/purchase-orders': typeof AuthenticatedClientPurchaseOrdersRoute
  '/_authenticated/client/users': typeof AuthenticatedClientUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/client'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/balance-confirmations'
    | '/admin/clients'
    | '/admin/dispatch-queue'
    | '/admin/payments'
    | '/admin/po-formats'
    | '/admin/po-queue'
    | '/admin/products'
    | '/admin/rates'
    | '/admin/refund-letters'
    | '/admin/reports'
    | '/admin/settings'
    | '/client/balance-confirmations'
    | '/client/dispatches'
    | '/client/documents'
    | '/client/ledgers'
    | '/client/payments'
    | '/client/purchase-orders'
    | '/client/users'
    | '/admin/'
    | '/client/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/balance-confirmations'
    | '/admin/clients'
    | '/admin/dispatch-queue'
    | '/admin/payments'
    | '/admin/po-formats'
    | '/admin/po-queue'
    | '/admin/products'
    | '/admin/rates'
    | '/admin/refund-letters'
    | '/admin/reports'
    | '/admin/settings'
    | '/client/balance-confirmations'
    | '/client/dispatches'
    | '/client/documents'
    | '/client/ledgers'
    | '/client/payments'
    | '/client/purchase-orders'
    | '/client/users'
    | '/admin'
    | '/client'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/client'
    | '/_authenticated/'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/balance-confirmations'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/dispatch-queue'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/po-formats'
    | '/_authenticated/admin/po-queue'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/rates'
    | '/_authenticated/admin/refund-letters'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/client/balance-confirmations'
    | '/_authenticated/client/dispatches'
    | '/_authenticated/client/documents'
    | '/_authenticated/client/ledgers'
    | '/_authenticated/client/payments'
    | '/_authenticated/client/purchase-orders'
    | '/_authenticated/client/users'
    | '/_authenticated/admin/'
    | '/_authenticated/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/client/users': {
      id: '/_authenticated/client/users'
      path: '/users'
      fullPath: '/client/users'
      preLoaderRoute: typeof AuthenticatedClientUsersRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/client/purchase-orders': {
      id: '/_authenticated/client/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/client/purchase-orders'
      preLoaderRoute: typeof AuthenticatedClientPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/client/payments': {
      id: '/_authenticated/client/payments'
      path: '/payments'
      fullPath: '/client/payments'
      preLoaderRoute: typeof AuthenticatedClientPaymentsRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/client/ledgers': {
      id: '/_authenticated/client/ledgers'
      path: '/ledgers'
      fullPath: '/client/ledgers'
      preLoaderRoute: typeof AuthenticatedClientLedgersRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/client/documents': {
      id: '/_authenticated/client/documents'
      path: '/documents'
      fullPath: '/client/documents'
      preLoaderRoute: typeof AuthenticatedClientDocumentsRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/client/dispatches': {
      id: '/_authenticated/client/dispatches'
      path: '/dispatches'
      fullPath: '/client/dispatches'
      preLoaderRoute: typeof AuthenticatedClientDispatchesRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/client/balance-confirmations': {
      id: '/_authenticated/client/balance-confirmations'
      path: '/balance-confirmations'
      fullPath: '/client/balance-confirmations'
      preLoaderRoute: typeof AuthenticatedClientBalanceConfirmationsRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/refund-letters': {
      id: '/_authenticated/admin/refund-letters'
      path: '/refund-letters'
      fullPath: '/admin/refund-letters'
      preLoaderRoute: typeof AuthenticatedAdminRefundLettersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rates': {
      id: '/_authenticated/admin/rates'
      path: '/rates'
      fullPath: '/admin/rates'
      preLoaderRoute: typeof AuthenticatedAdminRatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/po-queue': {
      id: '/_authenticated/admin/po-queue'
      path: '/po-queue'
      fullPath: '/admin/po-queue'
      preLoaderRoute: typeof AuthenticatedAdminPoQueueRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/po-formats': {
      id: '/_authenticated/admin/po-formats'
      path: '/po-formats'
      fullPath: '/admin/po-formats'
      preLoaderRoute: typeof AuthenticatedAdminPoFormatsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dispatch-queue': {
      id: '/_authenticated/admin/dispatch-queue'
      path: '/dispatch-queue'
      fullPath: '/admin/dispatch-queue'
      preLoaderRoute: typeof AuthenticatedAdminDispatchQueueRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/balance-confirmations': {
      id: '/_authenticated/admin/balance-confirmations'
      path: '/balance-confirmations'
      fullPath: '/admin/balance-confirmations'
      preLoaderRoute: typeof AuthenticatedAdminBalanceConfirmationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBalanceConfirmationsRoute: typeof AuthenticatedAdminBalanceConfirmationsRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminDispatchQueueRoute: typeof AuthenticatedAdminDispatchQueueRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPoFormatsRoute: typeof AuthenticatedAdminPoFormatsRoute
  AuthenticatedAdminPoQueueRoute: typeof AuthenticatedAdminPoQueueRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminRatesRoute: typeof AuthenticatedAdminRatesRoute
  AuthenticatedAdminRefundLettersRoute: typeof AuthenticatedAdminRefundLettersRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminBalanceConfirmationsRoute:
      AuthenticatedAdminBalanceConfirmationsRoute,
    AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
    AuthenticatedAdminDispatchQueueRoute: AuthenticatedAdminDispatchQueueRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminPoFormatsRoute: AuthenticatedAdminPoFormatsRoute,
    AuthenticatedAdminPoQueueRoute: AuthenticatedAdminPoQueueRoute,
    AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
    AuthenticatedAdminRatesRoute: AuthenticatedAdminRatesRoute,
    AuthenticatedAdminRefundLettersRoute: AuthenticatedAdminRefundLettersRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedClientRouteRouteChildren {
  AuthenticatedClientBalanceConfirmationsRoute: typeof AuthenticatedClientBalanceConfirmationsRoute
  AuthenticatedClientDispatchesRoute: typeof AuthenticatedClientDispatchesRoute
  AuthenticatedClientDocumentsRoute: typeof AuthenticatedClientDocumentsRoute
  AuthenticatedClientLedgersRoute: typeof AuthenticatedClientLedgersRoute
  AuthenticatedClientPaymentsRoute: typeof AuthenticatedClientPaymentsRoute
  AuthenticatedClientPurchaseOrdersRoute: typeof AuthenticatedClientPurchaseOrdersRoute
  AuthenticatedClientUsersRoute: typeof AuthenticatedClientUsersRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
}

const AuthenticatedClientRouteRouteChildren: AuthenticatedClientRouteRouteChildren =
  {
    AuthenticatedClientBalanceConfirmationsRoute:
      AuthenticatedClientBalanceConfirmationsRoute,
    AuthenticatedClientDispatchesRoute: AuthenticatedClientDispatchesRoute,
    AuthenticatedClientDocumentsRoute: AuthenticatedClientDocumentsRoute,
    AuthenticatedClientLedgersRoute: AuthenticatedClientLedgersRoute,
    AuthenticatedClientPaymentsRoute: AuthenticatedClientPaymentsRoute,
    AuthenticatedClientPurchaseOrdersRoute:
      AuthenticatedClientPurchaseOrdersRoute,
    AuthenticatedClientUsersRoute: AuthenticatedClientUsersRoute,
    AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
  }

const AuthenticatedClientRouteRouteWithChildren =
  AuthenticatedClientRouteRoute._addFileChildren(
    AuthenticatedClientRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedClientRouteRoute: typeof AuthenticatedClientRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedClientRouteRoute: AuthenticatedClientRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
