/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedClientUsersRouteImport } from './routes/_authenticated/client/users'
import { Route as AuthenticatedClientPurchaseOrdersRouteImport } from './routes/_authenticated/client/purchase-orders'
import { Route as AuthenticatedClientPaymentsRouteImport } from './routes/_authenticated/client/payments'
import { Route as AuthenticatedClientLedgersRouteImport } from './routes/_authenticated/client/ledgers'
import { Route as AuthenticatedClientDocumentsRouteImport } from './routes/_authenticated/client/documents'
import { Route as AuthenticatedClientDispatchesRouteImport } from './routes/_authenticated/client/dispatches'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminRatesRouteImport } from './routes/_authenticated/admin/rates'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminPoQueueRouteImport } from './routes/_authenticated/admin/po-queue'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminDispatchQueueRouteImport } from './routes/_authenticated/admin/dispatch-queue'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin/clients'
import { Route as AuthenticatedAdminBalanceConfirmationsRouteImport } from './routes/_authenticated/admin/balance-confirmations'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated/admin/approvals'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/client/',
    path: '/client/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientUsersRoute =
  AuthenticatedClientUsersRouteImport.update({
    id: '/client/users',
    path: '/client/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientPurchaseOrdersRoute =
  AuthenticatedClientPurchaseOrdersRouteImport.update({
    id: '/client/purchase-orders',
    path: '/client/purchase-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientPaymentsRoute =
  AuthenticatedClientPaymentsRouteImport.update({
    id: '/client/payments',
    path: '/client/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientLedgersRoute =
  AuthenticatedClientLedgersRouteImport.update({
    id: '/client/ledgers',
    path: '/client/ledgers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientDocumentsRoute =
  AuthenticatedClientDocumentsRouteImport.update({
    id: '/client/documents',
    path: '/client/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientDispatchesRoute =
  AuthenticatedClientDispatchesRouteImport.update({
    id: '/client/dispatches',
    path: '/client/dispatches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRatesRoute = AuthenticatedAdminRatesRouteImport.update({
  id: '/admin/rates',
  path: '/admin/rates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPoQueueRoute =
  AuthenticatedAdminPoQueueRouteImport.update({
    id: '/admin/po-queue',
    path: '/admin/po-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDispatchQueueRoute =
  AuthenticatedAdminDispatchQueueRouteImport.update({
    id: '/admin/dispatch-queue',
    path: '/admin/dispatch-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/admin/clients',
    path: '/admin/clients',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBalanceConfirmationsRoute =
  AuthenticatedAdminBalanceConfirmationsRouteImport.update({
    id: '/admin/balance-confirmations',
    path: '/admin/balance-confirmations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/admin/approvals',
    path: '/admin/approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/balance-confirmations': typeof AuthenticatedAdminBalanceConfirmationsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/dispatch-queue': typeof AuthenticatedAdminDispatchQueueRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/po-queue': typeof AuthenticatedAdminPoQueueRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/client/dispatches': typeof AuthenticatedClientDispatchesRoute
  '/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/client/ledgers': typeof AuthenticatedClientLedgersRoute
  '/client/payments': typeof AuthenticatedClientPaymentsRoute
  '/client/purchase-orders': typeof AuthenticatedClientPurchaseOrdersRoute
  '/client/users': typeof AuthenticatedClientUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/balance-confirmations': typeof AuthenticatedAdminBalanceConfirmationsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/dispatch-queue': typeof AuthenticatedAdminDispatchQueueRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/po-queue': typeof AuthenticatedAdminPoQueueRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/client/dispatches': typeof AuthenticatedClientDispatchesRoute
  '/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/client/ledgers': typeof AuthenticatedClientLedgersRoute
  '/client/payments': typeof AuthenticatedClientPaymentsRoute
  '/client/purchase-orders': typeof AuthenticatedClientPurchaseOrdersRoute
  '/client/users': typeof AuthenticatedClientUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/balance-confirmations': typeof AuthenticatedAdminBalanceConfirmationsRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/dispatch-queue': typeof AuthenticatedAdminDispatchQueueRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/po-queue': typeof AuthenticatedAdminPoQueueRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/rates': typeof AuthenticatedAdminRatesRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/client/dispatches': typeof AuthenticatedClientDispatchesRoute
  '/_authenticated/client/documents': typeof AuthenticatedClientDocumentsRoute
  '/_authenticated/client/ledgers': typeof AuthenticatedClientLedgersRoute
  '/_authenticated/client/payments': typeof AuthenticatedClientPaymentsRoute
  '/_authenticated/client/purchase-orders': typeof AuthenticatedClientPurchaseOrdersRoute
  '/_authenticated/client/users': typeof AuthenticatedClientUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/balance-confirmations'
    | '/admin/clients'
    | '/admin/dispatch-queue'
    | '/admin/payments'
    | '/admin/po-queue'
    | '/admin/products'
    | '/admin/rates'
    | '/admin/reports'
    | '/admin/settings'
    | '/client/dispatches'
    | '/client/documents'
    | '/client/ledgers'
    | '/client/payments'
    | '/client/purchase-orders'
    | '/client/users'
    | '/admin/'
    | '/client/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/balance-confirmations'
    | '/admin/clients'
    | '/admin/dispatch-queue'
    | '/admin/payments'
    | '/admin/po-queue'
    | '/admin/products'
    | '/admin/rates'
    | '/admin/reports'
    | '/admin/settings'
    | '/client/dispatches'
    | '/client/documents'
    | '/client/ledgers'
    | '/client/payments'
    | '/client/purchase-orders'
    | '/client/users'
    | '/admin'
    | '/client'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/balance-confirmations'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/dispatch-queue'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/po-queue'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/rates'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/client/dispatches'
    | '/_authenticated/client/documents'
    | '/_authenticated/client/ledgers'
    | '/_authenticated/client/payments'
    | '/_authenticated/client/purchase-orders'
    | '/_authenticated/client/users'
    | '/_authenticated/admin/'
    | '/_authenticated/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/users': {
      id: '/_authenticated/client/users'
      path: '/client/users'
      fullPath: '/client/users'
      preLoaderRoute: typeof AuthenticatedClientUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/purchase-orders': {
      id: '/_authenticated/client/purchase-orders'
      path: '/client/purchase-orders'
      fullPath: '/client/purchase-orders'
      preLoaderRoute: typeof AuthenticatedClientPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/payments': {
      id: '/_authenticated/client/payments'
      path: '/client/payments'
      fullPath: '/client/payments'
      preLoaderRoute: typeof AuthenticatedClientPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/ledgers': {
      id: '/_authenticated/client/ledgers'
      path: '/client/ledgers'
      fullPath: '/client/ledgers'
      preLoaderRoute: typeof AuthenticatedClientLedgersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/documents': {
      id: '/_authenticated/client/documents'
      path: '/client/documents'
      fullPath: '/client/documents'
      preLoaderRoute: typeof AuthenticatedClientDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/dispatches': {
      id: '/_authenticated/client/dispatches'
      path: '/client/dispatches'
      fullPath: '/client/dispatches'
      preLoaderRoute: typeof AuthenticatedClientDispatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/rates': {
      id: '/_authenticated/admin/rates'
      path: '/admin/rates'
      fullPath: '/admin/rates'
      preLoaderRoute: typeof AuthenticatedAdminRatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/po-queue': {
      id: '/_authenticated/admin/po-queue'
      path: '/admin/po-queue'
      fullPath: '/admin/po-queue'
      preLoaderRoute: typeof AuthenticatedAdminPoQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dispatch-queue': {
      id: '/_authenticated/admin/dispatch-queue'
      path: '/admin/dispatch-queue'
      fullPath: '/admin/dispatch-queue'
      preLoaderRoute: typeof AuthenticatedAdminDispatchQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/balance-confirmations': {
      id: '/_authenticated/admin/balance-confirmations'
      path: '/admin/balance-confirmations'
      fullPath: '/admin/balance-confirmations'
      preLoaderRoute: typeof AuthenticatedAdminBalanceConfirmationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBalanceConfirmationsRoute: typeof AuthenticatedAdminBalanceConfirmationsRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminDispatchQueueRoute: typeof AuthenticatedAdminDispatchQueueRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPoQueueRoute: typeof AuthenticatedAdminPoQueueRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminRatesRoute: typeof AuthenticatedAdminRatesRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedClientDispatchesRoute: typeof AuthenticatedClientDispatchesRoute
  AuthenticatedClientDocumentsRoute: typeof AuthenticatedClientDocumentsRoute
  AuthenticatedClientLedgersRoute: typeof AuthenticatedClientLedgersRoute
  AuthenticatedClientPaymentsRoute: typeof AuthenticatedClientPaymentsRoute
  AuthenticatedClientPurchaseOrdersRoute: typeof AuthenticatedClientPurchaseOrdersRoute
  AuthenticatedClientUsersRoute: typeof AuthenticatedClientUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBalanceConfirmationsRoute:
    AuthenticatedAdminBalanceConfirmationsRoute,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminDispatchQueueRoute: AuthenticatedAdminDispatchQueueRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPoQueueRoute: AuthenticatedAdminPoQueueRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminRatesRoute: AuthenticatedAdminRatesRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedClientDispatchesRoute: AuthenticatedClientDispatchesRoute,
  AuthenticatedClientDocumentsRoute: AuthenticatedClientDocumentsRoute,
  AuthenticatedClientLedgersRoute: AuthenticatedClientLedgersRoute,
  AuthenticatedClientPaymentsRoute: AuthenticatedClientPaymentsRoute,
  AuthenticatedClientPurchaseOrdersRoute:
    AuthenticatedClientPurchaseOrdersRoute,
  AuthenticatedClientUsersRoute: AuthenticatedClientUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
